version: "2"
services:

    laravel:
      image: eboraas/laravel
      volumes:
        - ./src/laravel:/var/www/laravel
      
      links:
        - mysql
        
        
    

    lb:
     image: domecloud/openresty
     volumes:
        - ./src/nginx/conf:/opt/lixen/nginx/conf/
     ports:
      - 8000:80
     links:
      - pma
      - laravel
  


    mysql:
      image: mysql
      container_name: moph_mysql
      ports:
      - 3306:3306
      volumes:
        - ./tmp/mysql:/var/lib/mysql
      environment:
        - MYSQL_DATABASE=moph
        - MYSQL_ROOT_PASSWORD=password
   


    pma:
      image: phpmyadmin/phpmyadmin
      links:
        - mysql:db
      ports:
        - 8080:80